receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319

processors:
  batch:
    timeout: 5s
    send_batch_size: 5000
    send_batch_max_size: 5000
  resource/namespace:
    attributes:
      - key: service.namespace
        value: handson/sample-app
        action: upsert

exporters:
  otlphttp/mackerel:
    endpoint: https://otlp-vaxila.mackerelio.com
    compression: gzip
    headers:
      Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource/namespace, batch]
      exporters: [debug, otlphttp/mackerel]
