# 最終デモ用
# Mackerelのトレースにのみ送出します。イメージはDocker Hubに配置しています
services:
  hotrod1:
    image: ghcr.io/kmuto/hotrod:latest
    ports:
      - "127.0.0.1:8080:8080"
    command: ["all", "-S", "-m", "<p>注目するのはリクエストから配車に至るlatencyの値です。同じボタンを連打したときにlatencyが伸びていくのを確認し、トレースを見てみましょう。</p>"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - hotrod-example

  hotrod2:
    image: ghcr.io/kmuto/hotrod:latest
    ports:
      - "127.0.0.1:8081:8080"
    command: ["all", "-S", "-M", "-m", "<p>DBへのアクセスを改善したので連打してもlatency値は変わらなくなっています。さらにlatencyを下げるために何ができるでしょうか。トレースを見てみましょう。</p>"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - hotrod-example

  hotrod3:
    image: ghcr.io/kmuto/hotrod:latest
    ports:
      - "127.0.0.1:8082:8080"
    command: ["all", "-S", "-M", "-D", "100ms", "-W", "100", "-m", "<p>ルート検索の並列性を上げ、待ち時間を短縮しました。トレースを見てみましょう。</p>"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - hotrod-example

  hotrod4:
    image: ghcr.io/kmuto/hotrod:latest
    ports:
      - "127.0.0.1:8083:8080"
    command: ["all", "-S", "-M", "-D", "100ms", "-W", "100", "-L", "15", "-m", "<p>最後に、特定処理で障害を発生させてみます。何度かクリックしていると、詰まるような動作が発生します。ときには結果が返ってこないこともあります。トレースツール側で調べてみましょう。</p>"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - hotrod-example

  hotrod5:
    image: ghcr.io/kmuto/hotrod:latest
    ports:
      - "127.0.0.1:8084:8080"
    command: ["all", "-m", "<p>デモの前に実行する用。Redis timeoutを持つトレースを記録します。</p>"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - hotrod-example

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-col-demo.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "127.0.0.1:4318:4318"
    env_file: ../env.txt
    networks:
      - hotrod-example

networks:
  hotrod-example:
